---
abstract: 'Simple Stupid Spider base on Web::Scraper inspired by Dancer'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scrappy
requires:
  File::ShareDir: 0
  File::Slurp: 0
  HTML::TreeBuilder: 0
  Test::More: 0
  WWW::Mechanize::Plugin::Web::Scraper: 0
  YAML::Syck: 0
version: 0.59
